databases:
  - name: snooker-db
    plan: free

services:
  - type: web
    name: snooker-backend
    runtime: node
    rootDir: backend
    plan: starter
    buildCommand: npm ci && npm run build
    startCommand: npm run start:migrate
    autoDeploy: true
    envVars:
      # Use Render Postgres internal connection string for Prisma
      - key: DATABASE_URL
        fromDatabase:
          name: snooker-db
          property: connectionString
      # Comma-separated origins for CORS; set in dashboard for your domains
      - key: CORS_ORIGIN
        sync: false
      # Admin token to protect /admin endpoints; set securely in dashboard
      - key: ADMIN_TOKEN
        sync: false
      # Socket.io path (defaults to /socket.io)
      - key: SOCKET_IO_PATH
        value: "/socket.io"

  # Frontend static site (Vite React)
  - type: static_site
    name: snooker-frontend
    rootDir: frontend
    plan: free
    buildCommand: VITE_SOCKET_URL="https://${BACKEND_HOST}.onrender.com" VITE_API_URL="https://${BACKEND_HOST}.onrender.com" VITE_SOCKET_PATH="/socket.io" npm ci && npm run build
    staticPublishPath: dist
    envVars:
      - key: BACKEND_HOST
        fromService:
          name: snooker-backend
          type: web
          property: host