export type RegionKey = 'H' | 'K' | 'N' | 'I'
export interface DistrictItem { code: string; name: string }
export const DISTRICT_TABLE: Record<RegionKey, DistrictItem[]> = {
  H: [
    { code: 'HWC', name: '中西區' },
    { code: 'HWA', name: '灣仔' },
    { code: 'HED', name: '東區' },
    { code: 'HSD', name: '南區' },
    { code: 'HCT', name: '中環' },
    { code: 'HSW', name: '上環' },
    { code: 'HKT', name: '堅尼地城' },
    { code: 'HPF', name: '薄扶林' },
    { code: 'HSP', name: '西營盤' },
    { code: 'HAD', name: '金鐘' },
    { code: 'HCB', name: '銅鑼灣' },
    { code: 'HTH', name: '天后' },
    { code: 'HNP', name: '北角' },
    { code: 'HQB', name: '鰂魚涌' },
    { code: 'HSK', name: '筲箕灣' },
    { code: 'HSH', name: '西灣河' },
    { code: 'HCW', name: '柴灣' },
    { code: 'HSS', name: '小西灣' },
  ],
  K: [
    { code: 'KTS', name: '尖沙咀' },
    { code: 'KJD', name: '佐敦' },
    { code: 'KYM', name: '油麻地' },
    { code: 'KMK', name: '旺角' },
    { code: 'KPE', name: '太子' },
    { code: 'KSS', name: '深水埗' },
    { code: 'KCS', name: '長沙灣' },
    { code: 'KLZ', name: '荔枝角' },
    { code: 'KSX', name: '石硤尾' },
    { code: 'KHH', name: '紅磡' },
    { code: 'KWP', name: '黃埔' },
    { code: 'KHM', name: '何文田' },
    { code: 'KTK', name: '土瓜灣' },
    { code: 'KKD', name: '九龍城' },
    { code: 'KKT', name: '九龍塘' },
    { code: 'KLF', name: '樂富' },
    { code: 'KSP', name: '新蒲崗' },
    { code: 'KWD', name: '黃大仙' },
    { code: 'KWT', name: '觀塘' },
    { code: 'KLT', name: '藍田' },
    { code: 'KNT', name: '牛頭角' },
  ],
  N: [
    { code: 'NTM', name: '屯門' },
    { code: 'NYL', name: '元朗' },
    { code: 'NSW', name: '天水圍' },
    { code: 'NHK', name: '洪水橋' },
    { code: 'NKT', name: '錦田' },
    { code: 'NST', name: '新田' },
    { code: 'NSS', name: '上水' },
    { code: 'NFL', name: '粉嶺' },
    { code: 'NTP', name: '大埔' },
    { code: 'NSH', name: '沙田' },
    { code: 'NMS', name: '馬鞍山' },
    { code: 'NFT', name: '火炭' },
    { code: 'NTA', name: '大圍' },
    { code: 'NTW', name: '荃灣' },
    { code: 'NTY', name: '青衣' },
    { code: 'NKC', name: '葵涌' },
    { code: 'NSZ', name: '深井' },
    { code: 'NSG', name: '西貢' },
    { code: 'NTO', name: '將軍澳' },
    { code: 'NHH', name: '坑口' },
    { code: 'NTL', name: '調景嶺' },
    { code: 'NCW', name: '清水灣' },
    { code: 'NPS', name: '柏石角' },
    { code: 'NSP', name: '科學園' },
    { code: 'NTV', name: '大欖' },
    { code: 'NPG', name: '屏山' },
    { code: 'NPH', name: '八鄉' },
  ],
  I: [
    { code: 'ITC', name: '東涌' },
    { code: 'ICL', name: '赤鯨角' },
    { code: 'IDB', name: '愉景灣' },
    { code: 'ICA', name: '長洲' },
    { code: 'IPG', name: '坪洲' },
    { code: 'ILM', name: '南丫島' },
    { code: 'IMW', name: '梅窩' },
  ],
}
