ALTER TABLE "Member"
  ADD COLUMN IF NOT EXISTS "public_highbreak_enabled" BOOLEAN NOT NULL DEFAULT false;

ALTER TABLE "ClubProfile"
  ADD COLUMN IF NOT EXISTS "publicEnabled" BOOLEAN NOT NULL DEFAULT false;

ALTER TABLE "ClubProfile"
  ADD COLUMN IF NOT EXISTS "publicShowHighbreak" BOOLEAN NOT NULL DEFAULT true;

ALTER TABLE "ClubProfile"
  ADD COLUMN IF NOT EXISTS "publicShowTournaments" BOOLEAN NOT NULL DEFAULT true;

ALTER TABLE "ClubProfile"
  ADD COLUMN IF NOT EXISTS "publicShowLive" BOOLEAN NOT NULL DEFAULT true;

ALTER TABLE "SiteNotice"
  ADD COLUMN IF NOT EXISTS "homeShowLeaderboard" BOOLEAN NOT NULL DEFAULT true;

ALTER TABLE "SiteNotice"
  ADD COLUMN IF NOT EXISTS "homeShowClubList" BOOLEAN NOT NULL DEFAULT true;
